### PR TITLE
Add partial support for sections properties

### LINKED ISSUE #40: The property "svg" should be declared in the OPF file
If I add an `<svg>` tag to a section, the validator returns this error:

    ERROR(OPF-014): prova.epub/EPUB/xhtml/section0001.xhtml(-1,-1): The property "svg" should be declared in the OPF file.

That is, in `package.opf` there shoud be `properties="svg"` in the item tag:

        <item id="section0001.xhtml" href="xhtml/section0001.xhtml" media-type="application/xhtml+xml" properties="svg"></item>

I found no way to do it.

Thank you.

### PR DESCRIPTION
**Pull request by neclepsio**
Fixes #40.

### CODE REVIEW

**Comment by fmartingr** [comment]
Hey @neclepsio, thanks for the contribution! You need to fix all the references you included to your fork: `github.com/neclepsio/go-epub`. They should point to this repository, it should work on your development environment with that as well.

**Comment by neclepsio** [comment]
Ok, done.

**Comment by neclepsio** [comment]
> I am running with uncomment `form` part and I don't get any error on epubcheck. can you please send a code snippet that not work for you.

You also have to uncomment the relative section 4 of the test.

**Comment by neclepsio** [comment]
Is there a problem blocking this?

**Comment by neclepsio** [comment]
Closing and reopening on different branch.

**Pull request closed without merging**
